# Generated by Django 5.0.10 on 2024-12-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='elapsed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
