# Generated by Django 5.0.10 on 2025-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='record_status',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='status',
            new_name='record_status',
        ),
    ]
