# Generated by Django 5.0.10 on 2025-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipmentstatus_rename_status_customer_record_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='status',
            new_name='queue_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentstatus',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
