# Generated by Django 5.0.10 on 2024-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_queue_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('completed', 'completed'), ('processing', 'processing')], default='new', max_length=20),
        ),
    ]
