# Generated by Django 5.0.10 on 2024-12-31 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_queue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sus', 'Suspended'), ('deleted', 'Deleted')], max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='queue',
            name='elapsed_time',
        ),
        migrations.AddField(
            model_name='queue',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.customer'),
            preserve_default=False,
        ),
    ]
