# Generated by Django 5.0.10 on 2025-01-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_remove_queue_elapsed_time_queue_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'first_name': True, 'id': True}, on_delete=django.db.models.deletion.PROTECT, to='api.customer'),
        ),
    ]
