services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./../../postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'machine_qa_api'
    ports:
      - '5432:5432'
volumes:
  postgres_data: